library(ggplot2)
library(reshape2)
args<-(commandArgs(TRUE))
#data<-read.csv(file<-args[1],sep="\t",header=FALSE)
data<-read.delim(file<-args[1],sep="\t",header=FALSE,encoding = "utf-8")
colnames(data)<- c("chrom","length","snp_p","VAF","heterozygosity")
Snp_hist<-ggplot(data,aes(x=VAF),cex.axis=1.5)+geom_histogram(binwidth=0.01, colour="black", fill="PaleGreen",alpha=0.3) +geom_vline(aes(xintercept=mean(VAF, na.rm=T)),color="red", linetype="dashed", size=1)+ theme_bw()+theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text.x = element_text(size = 15),axis.text.y = element_text(size = 15),axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15))+labs(x="VAF (Variant allele fraction)",y="Contig numbers")
pdf(args[2],width = 10,height = 7)
print(Snp_hist)
dev.off()